### ISSUE TITLE
context construction relies on environment variables present in process

### ISSUE THREAD

**Issue by ShelbyZ** [dkundel/twilio-run#1]
It would be ideal if the value could be pulled from the .env file if present otherwise try to read from the process.env to allow users who don't dump variables into process space the ability to get a twilio client object.

https://github.com/dkundel/twilio-run/blob/9a1a19be961647f1dcb2761be869d2611cbc391e/src/route.js#L18

**Comment by ShelbyZ** [comment]
This was a misunderstanding on my part.

**Comment by dkundel** [comment]
You should be using `context.getTwilioClient()` for that behavior actually :)

Cheers,
Dominik
